### ISSUE TITLE
The requested URL /user/index.php was not found on this server.

### ISSUE THREAD

**Issue by MaimaKhan** [moodleuulm/moodle-local_bulkenrol#11]
Hello
I just installed for my Moodle 3.4.1  this plugin "User bulk enrolment"  and it is life saving when I pasted Email Address in Bulk Enrollment  Everything is working fine with search. But When I press Enroll Users Button and here comes this page
The requested URL /user/index.php was not found on this server.
When I hit back page users are registered but why this Page I am viewing? Please help me with this.

**Comment by rtschu** [comment]
Hey, I believe this bug was introduced in 8cdbafc466dac9d09b6f881fe55327bcb0ac1077 where the redirecting url was changed from `$CFG->wwwroot .'/local/bulkenrol/index.php?id='.$id` to `'/bulkenrol/index.php?id='.$id`

Luckily it only causes the feedback to redirect to a wrong page, so the core functions of the plugin still work fine.

Theres a fix available at https://github.com/rtschu/moodle-local_bulkenrol/tree/fixredirect

**Comment by abias** [comment]
Hi @MaimaKhan and @rtschu ,

I am sorry that this redirection flaw was introduced. It only affected Moodle installations which are installed in subdirectories and is fixed with @rtschu 's pull request.
