### ISSUE TITLE
Problems with Bulk Enroll

### ISSUE THREAD

**Issue by scotthardwick** [moodleuulm/moodle-local_bulkenrol#8]
Hi!

I have been testing the local_bulkenrol for possible use at my institution and I have encountered a few problems. Some of these may be bugs, others may be by design.

1.  If you put in the following two lines for example
Nodata
Nodata
It will return a message to you that it didn’t find any email address, but then you press Enroll Users and it gives you a message it was successful.  This is a bit misleading.

2. If you have already loaded individuals into
#MyGroup
email@myemail.com
and then run another load with
#mygroup
anotheremail@myemail.com
It creates two different groups named mygroup with different capitalization.  I tried this in just the standard way to create groups and apparently Moodle allows this, which seems weird.

3. A larger percentage of our classes take place in a metaclass, with it inheriting the students from 2 or more subclasses.  If I do a bulkenrol of students to place the students into some groups, on the confirmation screen it comes back and says yes the student is already enrolled and we will put them in their group.   After hitting Enroll Users, rather than just putting them in their group, it also manually enrolls them into the MetaClass as well (giving the student now two enrollments into the class!).  I assume it would do the same type of thing if the students were in a cohort attached to the class.  I am assuming this is all accidental.

4. Do you know if yall might at some point add on the confirmation screen that the teacher is about to create new groups named x,y,z?  This way they might catch if they have mistyped a group name and are about to create a group they don’t want.  Currently on the confirmation screen it just says “GroupName(User added to group)” and doesn’t acknowledge that it is a previously non-existent group and about to be created.

5. Do you know if yall might have any future plans on the roadmap to allow teachers to supply a username or idnumber instead of the email address? This would be very useful.

Thanks so much for reading this and thank you for taking the time to create and release Moodle plugins for the community!
Scott

**Comment by abias** [comment]
Hi Scott, 

thank you very much for your input.

Let me handle all items one by one:

1. I think this can be considered as a bug. If there isn't any valid email address in the list, then the "Enrol users" button shouldn't be there at all. You should only be able to go back to the list input page to fix the list.
I will try to make sure to have this fixed.

2. Well, as you have written, the plugin's behaviour is the same as Moodle core's behaviour: It seems to handle group names case-sensitive. We can argue if this is a weird behaviour or a feature, but if it has to be fixed, then it has to be fixed in Moodle core and not in this plguin.

3. I think this can also be considered as bug or at least as unexpected behaviour. Am I right to assume that your expectation would be that the plugin only adds the users to the groups and does neither touch the meta enrolment / cohort enrolment instance nor create another manual enrolment instance?

4. I think the information if the group the user will be added to already exists or will be created on-the-fly might be easy to add. At least, the request makes sense to me.
I will try to make sure to have this done.

5. This is a valid request. However, I am unsure if we can do anything about it currently. If you look at https://github.com/moodleuulm/moodle-local_bulkenrol#limitations, you will see that this limitation is known. It is based on the fact that we only needed to submit list of email addresses in our usage scenarios. There are other plugins our there which accept other user profile fields, but which at the same time have other shortcomings.
Checking only the username in addition to the email address would be probably quite simple as both fields can be distinguished by the existence / absence of the @ sign. Adding other fields like the idnumber to the mix will surely need an extension of the list syntax or the list form as you need to indicate which user profile field has to be checked.

Cheers,
Alex

**Comment by scotthardwick** [comment]
Alex,
Thanks so much for your detailed reply!
1. Thanks you!
2. I will work through the Moodle Forums to see if the community sees this as desirable behavior and then if needed put in a Tracker item on this.
3. Yes, you are correct.  This is exactly what I am expecting.
4. Thank you!
5. Thanks, I understand! Does ULM take code contributions? If so, I might work on this later this semester. If not, that is ok! ;-)

Completely unrelated to the above, I was reading through Tracker yesterday and found comments you posted on MDL-34634.   I am curious if you ever developed and released this code?  If better to take this offline, please feel free to reach out to me at scott.hardwick at lsus.edu

Best,
Scott

**Comment by scotthardwick** [comment]
An interesting followup note on my question about MDL-34634. I found out late yesterday that Moodle 3.7 will have Course MetaData fields!

**Comment by abias** [comment]
Hi Scott,

thank you for your feedback.
I will schedule it internally to have item 1, 3 and 4 implemented / fixed.

> 5\. Thanks, I understand! Does ULM take code contributions? If so, I might work on this later this semester. If not, that is ok! ;-)

Basically: Yes, we do.
But: Our time to review contributions is limited and you might have to wait quite a while for us to review it. If you have time to write a patch for item 5, please create a dedicated issue here in Github first to discuss the implementation details to reduce our review time.

> Completely unrelated to the above, I was reading through Tracker yesterday and found comments you posted on MDL-34634. I am curious if you ever developed and released this code? If better to take this offline, please feel free to reach out to me at scott.hardwick at lsus.edu

Yes, this is really unrelated to this issue, that's why I will keep it short:
The project which I was talking about in MDL-34634 was cancelled unfortunately. If there would have been any results, we would have published them. 
I am aware that Custom course fields have been integrated recently into Moodle core and we will try any similar requirement to build on top of the core functionality.

Cheers,
Alex

**Comment by scotthardwick** [comment]
Thanks so much Alex!  ;-)

**Comment by abias** [comment]
Hi @scotthardwick ,

as a quick update: The development of these improvements had to be postponed. It is not forgotten, but is waiting for re-evaluation in fall.

Thanks,
Akex

**Comment by scotthardwick** [comment]
Hi @abias,
Thanks so much for the update! I do appreciate it.
Best
Scott

**Comment by abias** [comment]
Thank you @scotthardwick for your patience with this issue.

The discussed improvements were now implemented and pushed into the repo.
A new version of the plugin will be released to the Moodle plugin repo soon.
